# yamllint disable rule:line-length
name: "Run lintball in Docker"
description: "Keep your entire project tidy with a GitHub Action"
branding:
  icon: "align-left"
  color: "green"
inputs:
  check-all-files:
    description: "If true, the entire workspace is checked"
    required: true
    default: "false"
  committish:
    description: "The git commit hash, branch name, or tag name to check against"
    required: true
    default: "<auto>"
  default-branch:
    description: "The git branch to compare against. Usually master, main, or devel."
    required: true
    default: "<auto>"
  workspace:
    description: "The filesystem path to check. If not provided, will default to your project's path."
    required: true
    default: ""
  version:
    description: "The version of lintball to use. If not provided, will default to a hardcoded version corresponding to the run-lintball action version."
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - run: |
        if [[ "$(git rev-parse --is-shallow-repository)" == "true" ]]; then
          status=0
          git fetch origin ${GITHUB_REF_NAME} --unshallow || git fetch origin ${GITHUB_REF_NAME} --depth=10 || status=$?
          if [ $status -ne 0 ]; then
            echo "Failed to fetch the full history of the repository"
            echo "Try adding 'fetch-depth: 0' to your checkout action."
            exit 1
          fi
        fi
      shell: bash
    - run: ${{ github.action_path }}/action.sh
      shell: bash
      env:
        INPUT_CHECK_ALL_FILES: ${{ inputs.check-all-files }}
        INPUT_COMMITTISH: ${{ inputs.committish }}
        INPUT_DEFAULT_BRANCH: ${{ inputs.default-branch }}
        INPUT_WORKSPACE: ${{ inputs.workspace }}
        INPUT_VERSION: ${{ inputs.version }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
